#端口号
server:
  port: 8080

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://118.190.144.204:3306/guo_zzzx
    username: root
    password: zymroot!
    driver-class-name: com.mysql.jdbc.Driver

#配置数据访问层
mybatis:
  #实体类所做包
  type-aliases-package: com.leo.microservicesimpleprovideruser.domain
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*Mapper.xml

#Spring-Boot Actustor暴露所有接口设置
management:
  endpoints:
    web:
      exposure:
       include: "*"

