#端口号
server:
  port: 8080

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://118.190.144.204:3306/leo
    username: root
    password: zymroot!
    driver-class-name: com.mysql.jdbc.Driver

  #用于指定注册到Eureka Server 上的应用名称
  application:
    name: microservice-provider-user

#配置数据访问层
mybatis:
  #实体类所做包
  type-aliases-package: com.leo.microservicesimpleprovideruser.domain
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*Mapper.xml

#Spring-Boot Actustor暴露所有接口设置
management:
  endpoints:
    web:
      exposure:
       include: "*"

#配置Eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://8761/eureka/
  #表示将自己的IP注册到Eureka server
  intance:
    prefer-ip-address: true

